"""add_champion_table_and_timeline_data

Revision ID: a855fcbd6fae
Revises: 
Create Date: 2026-01-22 07:59:51.429976+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a855fcbd6fae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_champions_champion_id'), 'champions', ['champion_id'], unique=True)
    op.create_table('invalid_api_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invalid_api_responses_created_at'), 'invalid_api_responses', ['created_at'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('data_version', sa.String(length=10), nullable=False),
    sa.Column('game_creation', sa.DateTime(), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('game_end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('game_mode', sa.String(length=50), nullable=False),
    sa.Column('game_name', sa.String(length=100), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('game_version', sa.String(length=50), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.String(length=10), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('tournament_code', sa.String(length=100), nullable=True),
    sa.Column('timeline_data', lol_data_center.database.models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.create_table('tracked_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('game_name', sa.String(length=100), nullable=False),
    sa.Column('tag_line', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('summoner_id', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('summoner_level', sa.Integer(), nullable=True),
    sa.Column('polling_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('last_match_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_players_puuid'), 'tracked_players', ['puuid'], unique=True)
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_db_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_creation', sa.DateTime(), nullable=False),
    sa.Column('summoner_name', sa.String(length=100), nullable=False),
    sa.Column('summoner_id', sa.String(length=100), nullable=True),
    sa.Column('riot_id_game_name', sa.String(length=100), nullable=True),
    sa.Column('riot_id_tagline', sa.String(length=10), nullable=True),
    sa.Column('profile_icon', sa.Integer(), nullable=False),
    sa.Column('summoner_level', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(length=50), nullable=False),
    sa.Column('champion_level', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_position', sa.String(length=20), nullable=False),
    sa.Column('individual_position', sa.String(length=20), nullable=False),
    sa.Column('lane', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=False),
    sa.Column('total_damage_dealt', sa.BigInteger(), nullable=False),
    sa.Column('total_damage_dealt_to_champions', sa.BigInteger(), nullable=False),
    sa.Column('total_damage_taken', sa.BigInteger(), nullable=False),
    sa.Column('damage_self_mitigated', sa.BigInteger(), nullable=False),
    sa.Column('largest_killing_spree', sa.Integer(), nullable=False),
    sa.Column('largest_multi_kill', sa.Integer(), nullable=False),
    sa.Column('killing_sprees', sa.Integer(), nullable=False),
    sa.Column('double_kills', sa.Integer(), nullable=False),
    sa.Column('triple_kills', sa.Integer(), nullable=False),
    sa.Column('quadra_kills', sa.Integer(), nullable=False),
    sa.Column('penta_kills', sa.Integer(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('gold_spent', sa.Integer(), nullable=False),
    sa.Column('total_minions_killed', sa.Integer(), nullable=False),
    sa.Column('neutral_minions_killed', sa.Integer(), nullable=False),
    sa.Column('vision_score', sa.Integer(), nullable=False),
    sa.Column('wards_placed', sa.Integer(), nullable=False),
    sa.Column('wards_killed', sa.Integer(), nullable=False),
    sa.Column('vision_wards_bought_in_game', sa.Integer(), nullable=False),
    sa.Column('turret_kills', sa.Integer(), nullable=False),
    sa.Column('turret_takedowns', sa.Integer(), nullable=False),
    sa.Column('inhibitor_kills', sa.Integer(), nullable=False),
    sa.Column('inhibitor_takedowns', sa.Integer(), nullable=False),
    sa.Column('baron_kills', sa.Integer(), nullable=False),
    sa.Column('dragon_kills', sa.Integer(), nullable=False),
    sa.Column('objective_stolen', sa.Integer(), nullable=False),
    sa.Column('total_heal', sa.BigInteger(), nullable=False),
    sa.Column('total_heals_on_teammates', sa.BigInteger(), nullable=False),
    sa.Column('total_damage_shielded_on_teammates', sa.BigInteger(), nullable=False),
    sa.Column('total_time_cc_dealt', sa.Integer(), nullable=False),
    sa.Column('time_ccing_others', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('first_blood_kill', sa.Boolean(), nullable=False),
    sa.Column('first_blood_assist', sa.Boolean(), nullable=False),
    sa.Column('first_tower_kill', sa.Boolean(), nullable=False),
    sa.Column('first_tower_assist', sa.Boolean(), nullable=False),
    sa.Column('game_ended_in_surrender', sa.Boolean(), nullable=False),
    sa.Column('game_ended_in_early_surrender', sa.Boolean(), nullable=False),
    sa.Column('time_played', sa.Integer(), nullable=False),
    sa.Column('item0', sa.Integer(), nullable=False),
    sa.Column('item1', sa.Integer(), nullable=False),
    sa.Column('item2', sa.Integer(), nullable=False),
    sa.Column('item3', sa.Integer(), nullable=False),
    sa.Column('item4', sa.Integer(), nullable=False),
    sa.Column('item5', sa.Integer(), nullable=False),
    sa.Column('item6', sa.Integer(), nullable=False),
    sa.Column('summoner1_id', sa.Integer(), nullable=False),
    sa.Column('summoner2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_db_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['tracked_players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'puuid', name='uq_match_participant')
    )
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_puuid'), 'match_participants', ['puuid'], unique=False)
    op.create_index('ix_participant_puuid_game_creation', 'match_participants', ['puuid', 'game_creation'], unique=False)
    op.create_table('player_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('max_kills', sa.Integer(), nullable=False),
    sa.Column('max_kills_match_id', sa.String(length=50), nullable=True),
    sa.Column('max_deaths', sa.Integer(), nullable=False),
    sa.Column('max_deaths_match_id', sa.String(length=50), nullable=True),
    sa.Column('max_assists', sa.Integer(), nullable=False),
    sa.Column('max_assists_match_id', sa.String(length=50), nullable=True),
    sa.Column('max_kda', sa.Float(), nullable=False),
    sa.Column('max_kda_match_id', sa.String(length=50), nullable=True),
    sa.Column('max_cs', sa.Integer(), nullable=False),
    sa.Column('max_cs_match_id', sa.String(length=50), nullable=True),
    sa.Column('max_damage_to_champions', sa.BigInteger(), nullable=False),
    sa.Column('max_damage_match_id', sa.String(length=50), nullable=True),
    sa.Column('max_vision_score', sa.Integer(), nullable=False),
    sa.Column('max_vision_match_id', sa.String(length=50), nullable=True),
    sa.Column('max_gold', sa.Integer(), nullable=False),
    sa.Column('max_gold_match_id', sa.String(length=50), nullable=True),
    sa.Column('min_deaths', sa.Integer(), nullable=True),
    sa.Column('min_deaths_match_id', sa.String(length=50), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('total_losses', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['tracked_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_records')
    op.drop_index('ix_participant_puuid_game_creation', table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_puuid'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_tracked_players_puuid'), table_name='tracked_players')
    op.drop_table('tracked_players')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_invalid_api_responses_created_at'), table_name='invalid_api_responses')
    op.drop_table('invalid_api_responses')
    op.drop_index(op.f('ix_champions_champion_id'), table_name='champions')
    op.drop_table('champions')
    # ### end Alembic commands ###
